"""final schema with timezone aware datetimes

Revision ID: 72a9f9136cc0
Revises: 
Create Date: 2026-03-24 05:25:04.340621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a9f9136cc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('hero_type', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name')
    )
    op.create_table('players',
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('account_name'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('leaderboard_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('badge_level', sa.Integer(), nullable=True),
    sa.Column('ranked_rank', sa.Integer(), nullable=True),
    sa.Column('ranked_subrank', sa.Integer(), nullable=True),
    sa.Column('top_hero_ids', sa.String(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_name'], ['players.account_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_snapshots_account_name'), 'leaderboard_snapshots', ['account_name'], unique=False)
    op.create_index(op.f('ix_leaderboard_snapshots_snapshot_at'), 'leaderboard_snapshots', ['snapshot_at'], unique=False)
    op.create_table('mmr_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('mmr', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_name'], ['players.account_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mmr_history_account_name'), 'mmr_history', ['account_name'], unique=False)
    op.create_index(op.f('ix_mmr_history_recorded_at'), 'mmr_history', ['recorded_at'], unique=False)
    op.create_table('player_hero_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_name'], ['players.account_name'], ),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_hero_stats_account_name'), 'player_hero_stats', ['account_name'], unique=False)
    op.create_index(op.f('ix_player_hero_stats_hero_id'), 'player_hero_stats', ['hero_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_hero_stats_hero_id'), table_name='player_hero_stats')
    op.drop_index(op.f('ix_player_hero_stats_account_name'), table_name='player_hero_stats')
    op.drop_table('player_hero_stats')
    op.drop_index(op.f('ix_mmr_history_recorded_at'), table_name='mmr_history')
    op.drop_index(op.f('ix_mmr_history_account_name'), table_name='mmr_history')
    op.drop_table('mmr_history')
    op.drop_index(op.f('ix_leaderboard_snapshots_snapshot_at'), table_name='leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_snapshots_account_name'), table_name='leaderboard_snapshots')
    op.drop_table('leaderboard_snapshots')
    op.drop_table('players')
    op.drop_table('heroes')
    # ### end Alembic commands ###
